name: Build and push to dockerhub
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: Build api
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: schizo99/pulseaudio
        tags: latest
